### PR TITLE
Fix negation

### PR DESCRIPTION
**Pull request by mjgp2**
Putting this out for comment :)

Valid non-complex not selectors like `tbody > tr:nth-of-type(n+6):not(:nth-of-type(17)) > td:nth-of-type(2) > a:not(:nth-of-type(2))` were failing because the optimization that tries to return the last element type or class was returning the wrong string.

Let me know how the three main files (normal, noqsa, base) files are generated if this is ok and I can update - are they all manually written?

### CODE REVIEW

**Comment by dperini** [comment]
@mjgp2 there is definitely a bug on my part there.
thank you for the help and digging in this. Your RE looks good.
I will try to put some time to test your changes and be back to you.

**Comment by dperini** [comment]
@mjgp2 all the 3 code paths are manually maintained (with help from cut, paste and diff processes):

- "full" - use browser's querySelector API when available and fall back to JS processing
- "noqsa" - use JS processing with no browser dependencies, for headless environments
- "base" - is the JS processing minimal code, only resolve ids, classes, names and attributes

all the code paths allow loading modules (see modules/ folder) that selectively extend the resolution of more selector types like pseudos, webforms/validation, jquery-extensions or expand the capabilities with "DOM traversal" methods or or use efficient caching strategies to improve speed in the resolution of frequently used selectors.

The "full" code path already includes the pseudos, shortcuts and caching modules.

**Comment by dperini** [comment]
@mjgp2 I have tested your changes today.
Unfortunately they produces several errors in the tests.
However the "dpseudos" regular expression does it's job correctly.
So I will keep that and try to fix the real bug that seems to be locate at line 1487:

    lastSlice = token.split(':not')[0];
which pretends the correct "lastSlice" is at position 0.
I am working on a fix for this.

Thank you again for the help in finding and making this bug evident with a test.

**Comment by mjgp2** [comment]
Ok can you point me at which tests? Is there a harness to run them all or do they need to be done manually in browser?

**Comment by mjgp2** [comment]
OK, I see the tests that are failing - I've used the CSS3 and WC3 selector tests against the noqsa file.

Updated the PR, they all pass now I think.

**Comment by dperini** [comment]
@mjgp2 
please check that the applied fix solves all your issues.
I ran all the test including your "negationtest.html" and everything seems to be OK!
I made some changes to the original PR because i believe there was a previous bug in my logic.
Thank you for the help and for contributing a fix for this.

**Comment by mjgp2** [comment]
@dperini - appears all is working OK now on master :)

Can you get a version bump and I can open a PR on jsdom also?

Thanks for your help!

**Comment by dperini** [comment]
@mjgp2 thank you for testing it out.
I normally delay the release of a new version a few days.
Maybe somebody would want to chime in and suggest different changes/improvements.
I am also looking to the other pending PR about CSS numeric identifiers if worth including now.

**Comment by mjgp2** [comment]
Hey, how's are you getting on with this and the other PR? :)

**Comment by dperini** [comment]
@mjgp2 it is going slow ... unfortunately !
I have the other issue almost fixed too that's what delayed the release of a new version.
On top of it I the patch I wrote makes me feel a bad programmer. So expect a preview.
Maybe the two requests should be solved separately if you insist it must be now.

**Comment by dperini** [comment]
Your review would be appreciated also on the other PR for issue #99.
I published the "preview" code I was talking about in my previous message.
The changes are a bit fuzzy and there are repeated piece of code but it passes all the tests.
It will require more time to make the modifications to the other two paths (noqsa and base).
So maybe I will split that patch and cover it in another release and publish the fixed "negation" code.

Comments / suggestions ?

**Pull request closed without merging**
